name: BDP
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - ipykernel
  - ipywidgets
  - future
  - seaborn
  - confluent_kafka
  - sseclient