services:
  pyspark-stream:
    image: pyspark-stream
    container_name: pyspark-stream
    command: start-notebook.sh --NotebookApp.token='' # removes the need for access token. Only do this for development work in your local machine
    ports:
      - "8888:8888" # Jupyter UI
      - "4040:4040" # Spark UI. Every new context is on an incremental port (4041, 4042, etc)
    volumes:
      - "./mnt/:/home/jovyan/"
    env_file:
      - .env